package com.lmsoncloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ContentLibraryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContentLibraryAllPropertiesEquals(ContentLibrary expected, ContentLibrary actual) {
        assertContentLibraryAutoGeneratedPropertiesEquals(expected, actual);
        assertContentLibraryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContentLibraryAllUpdatablePropertiesEquals(ContentLibrary expected, ContentLibrary actual) {
        assertContentLibraryUpdatableFieldsEquals(expected, actual);
        assertContentLibraryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContentLibraryAutoGeneratedPropertiesEquals(ContentLibrary expected, ContentLibrary actual) {
        assertThat(expected)
            .as("Verify ContentLibrary auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContentLibraryUpdatableFieldsEquals(ContentLibrary expected, ContentLibrary actual) {
        assertThat(expected)
            .as("Verify ContentLibrary relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getResourceType()).as("check resourceType").isEqualTo(actual.getResourceType()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(actual.getLastModifiedBy()))
            .satisfies(e -> assertThat(e.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(actual.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContentLibraryUpdatableRelationshipsEquals(ContentLibrary expected, ContentLibrary actual) {}
}
