package com.lmsoncloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModuleAllPropertiesEquals(Module expected, Module actual) {
        assertModuleAutoGeneratedPropertiesEquals(expected, actual);
        assertModuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModuleAllUpdatablePropertiesEquals(Module expected, Module actual) {
        assertModuleUpdatableFieldsEquals(expected, actual);
        assertModuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModuleAutoGeneratedPropertiesEquals(Module expected, Module actual) {
        assertThat(expected)
            .as("Verify Module auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModuleUpdatableFieldsEquals(Module expected, Module actual) {
        assertThat(expected)
            .as("Verify Module relevant properties")
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(actual.getLastModifiedBy()))
            .satisfies(e -> assertThat(e.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(actual.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModuleUpdatableRelationshipsEquals(Module expected, Module actual) {
        assertThat(expected)
            .as("Verify Module relationships")
            .satisfies(e -> assertThat(e.getCourses()).as("check courses").isEqualTo(actual.getCourses()));
    }
}
